name: key_sharing
description: A Flutter project to show the differences between use or not use flutter keys when state exist in tree.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  get: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
   - family: GoogleSans
     fonts:
       - asset: assets/fonts/GoogleSans-Regular-v1.27.ttf
       - asset: assets/fonts/GoogleSans-Italic-v1.27.ttf
         style: italic
       - asset: assets/fonts/GoogleSans-Bold-v1.27.ttf
         weight: 700