name: key_sharing
description: A Flutter project to show the differences between use or not use flutter keys when state exist in tree.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

#  assets:
#   - assets/images/

  fonts:
   - family: GoogleSans
     fonts:
       - asset: assets/fonts/GoogleSans-Regular-v1.27.ttf
       - asset: assets/fonts/GoogleSans-Italic-v1.27.ttf
         style: italic
       - asset: assets/fonts/GoogleSans-Bold-v1.27.ttf
         weight: 700
